### PR TITLE
Adds ed_largest

### PR DESCRIPTION
**Pull request by Blake-Loveland**

### CODE REVIEW

**Comment by Blake-Loveland** [comment]
This adds in the newly provided attribute from earthdefine. I believe there is a timing requirement for merging this in, but am not fully sure what is affected by this.

**Comment by hampelm** [comment]
This does not need to get merged before release. It is a requirement for the new field showing in the feature service I believe, but that has not yet launched. And it would need the new table in place with the new column to be merged.

**Comment by vjcharles** [comment]
A note here that can help the FS update more easily. We currently use a pg view for the enhanced_ownership table. This approach allows the FS to return anything in that view without any code changes.

**Comment by Blake-Loveland** [comment]
Matt clarified how the schema change affects things and really it does not affect very much as the FS, API and web site are opt-in basically so I am moving ahead with getting the updated buildings live.

**Comment by Blake-Loveland** [comment]
> A note here that can help the FS update more easily. We currently use a pg view for the enhanced_ownership table. This approach allows the FS to return anything in that view without any code changes.

I like that approach, best of both worlds if I understand it correctly.

**Review by hampelm — APPROVED** [review]

**Pull request merged**
