### PR TITLE
Adds lat, lon, taxyear

### PR DESCRIPTION
**Pull request by Blake-Loveland**
NOT TO BE MERGED UNTIL August 10, 2021

Dear Reviewers, it is more of just an FYI so you see exactly what is suggested to become part of the Loveland Standard Parcel Schema.

### CODE REVIEW

**Review by rayLvisser — COMMENTED** [review]
I believe Blake almost mentioned this during the meeting: have we entertained the possibility of naming these `ll_lat` and `ll_lon`, to match our other derived columns like `ll_gisacre`?

**Comment by Blake-Loveland** [comment]
I am open to it, I am not sure why not really, I do not recall in-depth discussion on it honestly.

either way is good with me, why not do it that way, `ll_lat` and `ll_lon`

I personally think it is no problem to just make them that if no one can think of a good reason not to.

**Comment by lpuhl** [comment]
Chiming in to say that I am 100% in favor of naming them `ll_lon` and `ll_lat` for consistency!

**Comment by Blake-Loveland** [comment]
We did talk about the lat / lon change to ll_* and decided that usability for end users would be significantly easier for folks if we just kept them lat/lon as many tools and people auto recognize those headings.

We also discussed making them floats or a geometry type instead of text, and for similar reasons, tools auto displaying floats in certain ways, hurdles to working with geometries, we were best to leave them text to ensure consumers see and get the full set of digits that they can cast or format to floats/geometry types as needed.

**Pull request merged**
