### PR TITLE
Adds proposed padus public access flag

### PR DESCRIPTION
**Pull request by Blake-Loveland**

### CODE REVIEW

**Comment by Blake-Loveland** [comment]
This is needed so we can run the parcel util that sync's all the tables with our current schema.
That will get this attribute in all our tables.
Then the fill lbcs from padus parcel util can run without error.

**Review by hampelm — APPROVED** [review]
Looks good, maybe an example value in the future?

**Comment by Blake-Loveland** [comment]
Added the 4 possible values as examples.

**Review by rayLvisser — APPROVED** [review]
Looks good!

**Pull request merged**
