### PR TITLE
add additional address fields in DB

### PR DESCRIPTION
**Pull request by vjcharles**
Needed are description, sequence_number, example and possible categories if these aren't to be published.

I can update the support site with this info as these fields aren't in the [address schema page](https://support.regrid.com/parcel-data/address-schema) yet either.

@brambow noticed these 3 missing fields for the address layer as ArcGIS Pro is very particular about fields matching up with those in responses.

### CODE REVIEW

**Comment by hampelm** [comment]
Hmm, we don't deliver those three fields to customers

**Comment by vjcharles** [comment]
I think they are currently being returned in responses. If these get a category denoting they are internal, they can be filtered out when wdwot loads these yaml files. 
Currently the parcel schema filters out based on the category 'proposed' only. Is there another category key like 'internal' that could be used?

**Comment by hampelm** [comment]
No code implemented around it, but we've used `internal_only`, eg for `ll_no_cass`: https://github.com/loveland/schema/pull/58/files

**Review by hampelm — APPROVED** [review]
Looks good to me

**Pull request merged**
