### PR TITLE
Adds pii category to schema.yml

### PR DESCRIPTION
**Pull request by rayLvisser**
Does it seem like I missed any columns? When this came up for a client, @Blake-Loveland suggested also counting `address2` as a PII column, because it _may_ contain an uncleaned/unsorted owner name.

Also, based on previous category updates, I believe `schema.yml` is the only file I need to change, but I'd like confirmation on that.

### CODE REVIEW

**Comment by klovskim** [comment]
we def need to strip any mailadd stuff period I think.

**Comment by rayLvisser** [comment]
Did I miss one?

**Comment by Blake-Loveland** [comment]
This looks about right to me, glad I am not alone feeling like for us at least mailing address is pii.

**Comment by Blake-Loveland** [comment]
didn't look like you missed any to me.

**Review by Blake-Loveland — APPROVED** [review]

**Comment by Blake-Loveland** [comment]
oh, ya, add address2 if you ask me, it is useless really, it should only contain mistaken info basically,

**Pull request merged**
