### PR TITLE
removed USPS from descriptors

### LINKED ISSUE #26: Modify language around USPS in parcel details
@stephenandersondev here you go!

1) replace subhead title: replace `Mailing Information` with `Residential & Vacancy Indicators`

2) modify header: `Zoning & Land Use` > `Zoning, Land Use & Vacancy` (just realized that when sections are collapsed, I didn't know where vacancy data was)

3) modify attribute names:
`USPS Vacancy Indicator` > `Vacancy Indicator`
`USPS Vacancy Indicator Date` > `Vacancy Indicator Date`
`USPS Delivery Point Validation` > `Delivery Point Validation`

### PR DESCRIPTION
**Pull request by stephenandersondev**
closes #26 

linked to https://github.com/loveland/wdwot/pull/3686

### CODE REVIEW

**Comment by stephenandersondev** [comment]
Did we change our minds on this one? If so, I'll close it out.

**Comment by just-another-downer** [comment]
@stephenandersondev where are you seeing the convo around this? I'm personally still operating under the assumption that we don't want to be advertising USPS so prominently as part of the label (though you're right, I _do_ have a nagging half memory that someone (Sahana?) said something about wanting to keep it as is).

**Comment by stephenandersondev** [comment]
I can't seem to find the conversation around this either. I do remember that @sahana-murthy had an opinion on this I just don't remember what that was 😅

**Comment by stephenandersondev** [comment]
We can just re-open this if we change our mind

**Comment by just-another-downer** [comment]
Thanks Stephen! I spoke with Sahana yesterday and (although it's already embarrassingly fuzzy) I believe she also was of the opinion that we leave for now. So closing is perfect.

**Pull request closed without merging**
